apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ContainerConstraint
metadata:
  name: deny-illegal-container-constraint
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    namespaces:
    - default
  parameters:
    imagePrefixes:
    - kudohn
    - docker.io/kudohn
    groups:
    - mamezou-dev
