apiVersion: constraints.gatekeeper.sh/v1beta1
kind: LabelConstraint
metadata:
  name: required-label-constraint
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
    - default
  parameters:
    labels: ["mamezou.com/owner", "mamezou.com/system"]
