spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/frieza
    username: frieza
    password: frieza-pass
    initialization-mode: always
  batch:
    initialize-schema: always

mybatis:
  configuration:
    default-executor-type: batch

file:
  mount-path: /data

prometheus:
  enabled: false
  push-address: localhost:9091

