{
 "title": "Batch Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "バッチ実行時間",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "batch_job_duration_seconds {job = \"uploadJob\"}"
    }
   ]
  },
  {
   "title": "バッチ最終成功時刻",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "batch_job_last_success{job=\"uploadJob\"} * 1000"
    }
   ]
  },
  {
   "title": "バッチ最終失敗時刻",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 5 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "batch_job_last_failure{job=\"uploadJob\"} * 1000"
    }
   ]
  },
  {
   "title": "バッチ処理件数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "batch_job_processed_count {job=\"uploadJob\"}",
     "legendFormat": "処理件数"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 10 },
   "content": "\n[![Image from Gyazo](https://i.gyazo.com/782d59f2e022ca7c0c3eec3a79a1417e.png)](https://gyazo.com/782d59f2e022ca7c0c3eec3a79a1417e)\n\n",
   "targets": [
    {}
   ]
  }
 ]
}