apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: redis
data:
  master.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    dir /data
    logfile ""
  slave.conf: |
    slaveof redis-master-0.redis-headless 6379
    protected-mode no
    dir /data
