apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
    role: master
  ports:
  - name: redis
    port: 6379
    targetPort: redis
