github:
  host: api.github.com
  protocol: https
  media-type: application/vnd.github.v3+json
#  user: foo
#  password: bar
  repo-search-path: /search/repositories

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          # expose prometheus metrics endpoint
          - prometheus


opentracing:
  jaeger:
    enabled: false
    service-name: github-servicve
    const-sampler:
      decision: true # always sampling for verification
    udp-sender:
      host: localhost
      port: 6831

logging:
  level:
    io.opentracing.contrib.tracerresolver.TracerResolver: error
