apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-role
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "pods/log", "pods/status", "services", "endpoints", "deployments", "replicasets", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]
