apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sre-role
rules:
- apiGroups: ["", "apps"]
  resources: 
  - "pods"
  - "pods/log"
  - "pods/exec"
  - "pods/status"
  - "services"
  - "endpoints"
  - "deployments" 
  - "replicasets"
  - "configmaps"
  - "persistentvolumeclaims"
  verbs: ["get", "list", "watch", "delete", "deletecollection"]
- apiGroups: ["", "apps", "extensions", "rbac.authorization.k8s.io", "storage.k8s.io", "networking.k8s.io"]
  resources: 
  - "ingress"
  - "events"
  - "nodes"
  - "namespaces"
  - "secrets"
  - "storageclasses"
  - "persistentvolumes"
  - "serviceaccounts"
  - "roles"
  - "rolebindings"
  - "clusterroles"
  - "clusterrolebindings"
  verbs: ["get", "list", "watch", "create", "patch", "update", "delete", "deletecollection"]
