apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: repo-search-ui
data:
  repo-search-ui.conf: |-
    server {
        listen       80;
        server_name  localhost;
        location / {
            root   /usr/share/nginx/html;
            index  index.html;
        }
        location /health {
            access_log off;
            return 200 "UP\n";
        }      
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
