apiVersion: v1
kind: Service
metadata:
  name: repo-search-ui
  labels:
    app: repo-search-ui
spec:
  type: NodePort
  selector:
    app: repo-search-ui
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
