---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-test1
  labels:
    name: nfs-test
spec:
  containers:
  - name: nfs-test
    image: busybox
    command:
      - sh
      - -c
      - sleep 3600
    volumeMounts:
      - name: nfs-volume
        mountPath: /data
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc

---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-test2
  labels:
    name: nfs-test
spec:
  containers:
  - name: nfs-test
    image: busybox
    command:
      - sh
      - -c
      - sleep 3600
    volumeMounts:
      - name: nfs-volume
        mountPath: /data
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc

