apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: githubsearches.mamezou.com
spec:
  group: mamezou.com
  names:
    kind: GithubSearch
    listKind: GithubSearchList
    plural: githubsearches
    singular: githubsearch
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GithubSearch is the Schema for the githubsearches API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GithubSearchSpec defines the desired state of GithubSearch
          properties:
            appVersion:
              type: string
            clusterSize:
              format: int32
              type: integer
            githubSecret:
              type: string
            serviceType:
              type: string
          type: object
        status:
          description: GithubSearchStatus defines the observed state of GithubSearch
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
