apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-logback-config
data:
  logback-spring.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
        ​
        <appender name="logstash" class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
        </appender>
        ​
        <root level="INFO">
            <appender-ref ref="logstash"/>
        </root>
    </configuration>