apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heavy
  labels:
    name: heavy
spec:
  replicas: 5
  template:
    metadata:
      labels:
        name: heavy
    spec:
      affinity:
        nodeAffinity:
          # GPUノードに優先的に配置するAffinity
          # preferredDuringSchedulingIgnoredDuringExecution:
          # - weight: 100
          #   preference:
          #     matchExpressions:
          #     - key: gpu
          #       operator: Exists
          # GPUノードに配置するAffinity(Hard)
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu
                operator: Exists
      # GPUのtaintが存在するNodeにスケジューリングされることを許容  
      tolerations:
        - key: gpu
          operator: Exists
          effect: NoSchedule
      containers:
      - image: kennethreitz/httpbin
        name: http-bin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: normal
  labels:
    name: normal
spec:
  replicas: 5
  template:
    metadata:
      labels:
        name: normal
    spec:
      containers:
      - image: kennethreitz/httpbin
        name: http-bin
