apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-search-ui
spec:
  template:
    spec:
      containers:
      - name: repo-search-ui
        resources: 
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m
