apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    app: api-gateway
data:
  # backend service
  serviceURL: http://github-service.default.svc.cluster.local/github
  # redis for cache
  redisHost: redis-master.redis.svc.cluster.local
  redisPort: "6379"

