apiVersion: v1
kind: Service
metadata:
  name: mock
spec:
  selector:
    name: mock
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mock
  labels:
    name: mock
spec:
  template:
    metadata:
      labels:
        name: mock
    spec:
      containers:
      - image: kennethreitz/httpbin
        name: http-bin
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mock-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: mock.cluster.local
      http:
        paths:
          - path: /mock/(.*)
            backend:
              serviceName: mock
              servicePort: 80
