apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - cloud.frieza.dev
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - cloud.frieza.dev
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer