apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encryptの証明書発行URL(ステージング環境用なのでTrustedではない)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Let's Encryptに登録するアドレス
    email: ''
    # Let's Encryptへのアクセス用のクレデンシャル(Cert Managerが自動生成する)
    privateKeySecretRef:
      name: letsencrypt-staging
    # HTTP-01 challenge(証明書発行するためにはそのドメインを所有しているという証明が必要)
    # https://letsencrypt.org/docs/challenge-types/
    # まずはCert ManagerがLet's EncryptのValidation要求に応えてくれる
    solver:
      http01: 
       ingressName: ingress